services:
  database:
    image: postgres:latest
    container_name: database
    restart: always # always restart the container
    ports:
      - 5432:5432
    env_file:
      - .env

  nestjs:
    build: .
    container_name: nestjs
    restart: always
    environment:
      - TZ=America/Sao_Paulo
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - database
